from __future__ import annotations

import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import Any

from app.services.policy_packs import PolicyPack
from app.services.terraform_plan import get_attr


INSTANCE_MONTHLY = {
    "t3.micro": 7.49,
    "t3.small": 14.98,
    "t3.medium": 29.95,
    "m7i.large": 70.08,
    "m7i.xlarge": 140.16,
    "m7i.2xlarge": 280.32,
    "m7i.4xlarge": 560.64,
    "r7g.large": 78.84,
    "r7g.xlarge": 157.68,
    "r7g.2xlarge": 315.36,
}


def estimate_cost_delta(
    resource_changes: list[dict[str, Any]],
    policy_pack: PolicyPack,
    plan_path: str | None = None,
) -> dict[str, Any]:
    infracost = _estimate_with_infracost(plan_path, policy_pack)
    if infracost:
        return infracost

    line_items: list[dict[str, Any]] = []
    monthly_delta = 0.0
    for resource in resource_changes:
        estimate = _estimate_resource(resource)
        if not estimate:
            continue
        action_factor = _action_factor(resource.get("change", {}).get("actions", []))
        delta = round(estimate["monthly_cost"] * action_factor, 2)
        monthly_delta += delta
        line_items.append(
            {
                "resource_address": resource.get("address"),
                "resource_type": resource.get("type"),
                "description": estimate["description"],
                "monthly_delta": delta,
                "confidence": estimate["confidence"],
                "source": "heuristic",
            }
        )
    monthly_delta = round(monthly_delta, 2)
    return {
        "currency": "USD",
        "monthly_delta": monthly_delta,
        "annual_delta": round(monthly_delta * 12, 2),
        "threshold": policy_pack.max_monthly_delta,
        "over_threshold": monthly_delta > policy_pack.max_monthly_delta,
        "source": "infracost_cli" if False else "heuristic_fallback",
        "message": "Heuristic estimate used. Configure Infracost CLI for provider-grade pricing.",
        "line_items": sorted(line_items, key=lambda item: abs(item["monthly_delta"]), reverse=True),
    }


def _estimate_with_infracost(plan_path: str | None, policy_pack: PolicyPack) -> dict[str, Any] | None:
    if not plan_path or not os.getenv("INFRACOST_API_KEY") or shutil.which("infracost") is None:
        return None
    path = Path(plan_path)
    if not path.exists():
        return None
    try:
        completed = subprocess.run(
            ["infracost", "breakdown", "--path", str(path), "--format", "json"],
            capture_output=True,
            text=True,
            timeout=120,
            check=True,
        )
        payload = json.loads(completed.stdout)
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired, json.JSONDecodeError):
        return None

    total = _money(payload.get("totalMonthlyCost"))
    prior = _money(payload.get("pastTotalMonthlyCost"))
    monthly_delta = round(total - prior, 2)
    line_items = _infracost_line_items(payload)
    return {
        "currency": "USD",
        "monthly_delta": monthly_delta,
        "annual_delta": round(monthly_delta * 12, 2),
        "threshold": policy_pack.max_monthly_delta,
        "over_threshold": monthly_delta > policy_pack.max_monthly_delta,
        "source": "infracost_cli",
        "message": "Cost delta generated by Infracost CLI from the Terraform plan JSON.",
        "line_items": line_items,
    }


def _money(value: Any) -> float:
    if value is None or value == "":
        return 0.0
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def _infracost_line_items(payload: dict[str, Any]) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    for project in payload.get("projects", []):
        for resource in project.get("breakdown", {}).get("resources", []):
            items.append(
                {
                    "resource_address": resource.get("name"),
                    "resource_type": resource.get("resourceType"),
                    "description": resource.get("name") or "Infracost resource",
                    "monthly_delta": _money(resource.get("monthlyCost")),
                    "confidence": 0.9,
                    "source": "infracost",
                }
            )
    return sorted(items, key=lambda item: abs(item["monthly_delta"]), reverse=True)


def _estimate_resource(resource: dict[str, Any]) -> dict[str, Any] | None:
    resource_type = resource.get("type")
    if resource_type == "aws_nat_gateway":
        return {"monthly_cost": 32.4, "description": "NAT Gateway hourly baseline", "confidence": 0.78}
    if resource_type == "aws_opensearch_domain":
        return {"monthly_cost": 180.0, "description": "OpenSearch small domain baseline", "confidence": 0.55}
    if resource_type == "aws_ebs_volume":
        size = get_attr(resource, "size") or 0
        iops = get_attr(resource, "iops") or 0
        monthly = (float(size) * 0.08) + max(0, float(iops) - 3000) * 0.005
        return {"monthly_cost": monthly, "description": f"EBS {size} GiB plus provisioned IOPS", "confidence": 0.68}
    if resource_type == "aws_instance":
        instance_type = get_attr(resource, "instance_type")
        monthly = INSTANCE_MONTHLY.get(str(instance_type), 65.0)
        return {"monthly_cost": monthly, "description": f"EC2 {instance_type or 'unknown'} monthly baseline", "confidence": 0.58}
    if resource_type == "aws_db_instance":
        instance_class = str(get_attr(resource, "instance_class") or "db.t3.medium")
        monthly = 55.0
        if "large" in instance_class:
            monthly = 120.0
        if "xlarge" in instance_class:
            monthly = 240.0
        if get_attr(resource, "multi_az") is True:
            monthly *= 2
        return {"monthly_cost": monthly, "description": f"RDS {instance_class} baseline", "confidence": 0.52}
    return None


def _action_factor(actions: list[str]) -> float:
    if "delete" in actions and "create" not in actions:
        return -1.0
    if "create" in actions:
        return 1.0
    if "update" in actions:
        return 0.25
    return 0.0
